name: Publish release
on:
  workflow_run:
    workflows: [ 'Build release' ]
    branches:
      - '*'
    types:
      - completed

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve versions
        run: |
          echo "FB_LINUX_VERSION=v$(awk -F, '/^linux,/ {print $2}' nr_fb_version)"  >> $GITHUB_ENV
          echo "FB_WIN_VERSION=$(awk -F, '/^windows,/ {print $2}' nr_fb_version)"  >> $GITHUB_ENV
          echo "NRFB_ARTIFACT_VERSION=$(awk -F, '/^artifact,/ {print $2}' nr_fb_version)"  >> $GITHUB_ENV

      - name: Print versions
        run: |
          echo "FB_LINUX: ${{ env.FB_LINUX_VERSION }}"
          echo "FB_WIN: ${{ env.FB_WIN_VERSION}}"
          echo "NR ARTIFACT: ${{ env.NRFB_ARTIFACT_VERSION }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NRFB_ARTIFACT_VERSION }}
          release_name: nrfb v${{ env.NRFB_ARTIFACT_VERSION }}
          body: |
            Included into this Release
            - FluentBit Linux Version: ${{ env.FB_LINUX_VERSION }}
            - FluentBit Windows Version: v${{ env.FB_WIN_VERSION}}
          draft: false
          prerelease: false

  publish-distro-artifacts:
    name: publish distro artifacts
    needs: create-release
    strategy:
      max-parallel: 48
      fail-fast: true
      matrix:
        distro: [ amazonlinux/2, ubuntu/18.04 ]

    runs-on: [ ubuntu-latest ] #self-hosted, Linux, X64, packet-builder]
    steps:
      - uses: frabert/replace-string-action@master
        id: formatted_distro
        with:
          pattern: '(.*)\/(.*)$'
          string: "${{ matrix.distro }}"
          replace-with: '$1-$2'
          flags: 'g'

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Move artifacts to main folder
        run: |
          mv artifacts/**/*.tar.gz .
          ls -la

      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          distro-name: ${{ steps.formatted_distro.outputs.replaced }}
          upload-url: ${{ needs.create-release.outputs.upload_url }}
        with:
          upload_url: ${{ env.upload-url }}
          asset_path: ./nrfb-linux-${{env.distro-name}}.tar.gz
          asset_name: nrfb-linux-${{env.distro-name}}.tar.gz
          asset_content_type: application/gzip
